In [1]:
%matplotlib notebook

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
def L_matrix():
    n=50
    A=np.zeros([n,n],dtype=np.int)
    for i in range(50):
        for j in range(50):
            if(i!=j):
                A[i,j]=np.random.binomial(1, 0.1, 1)
    
    A=A+A.T
    for i in range(50):
        for j in range(50):
            if(A[i,j]>0):
                A[i,j]=1
                
    D=np.sum(A,axis = 1)
    for i in range(50):
        A[i,i]=-D[i]
        
    i=np.random.normal(50, 10,50)
    
    
    return -A,i

In [4]:
L_set=np.array(np.zeros([1,50,50]),ndmin=3)
i_set=np.array(np.zeros([1,50]),ndmin=2)
for number_L in range(50):
    L,i=L_matrix()
    i_set=np.append(i_set,[i],axis=0)
    L_set=np.append(L_set,[L],axis=0)

In [5]:
#L
for x in range(50):
    data_L=pd.DataFrame(L_set[x+1,:,:])
    data_L.to_csv("fig6/L_"+str(x+1)+".csv")
#i
data_I=pd.DataFrame(i_set)
data_I.to_csv("fig6/I.csv")

a=np.array([],ndmin=2)#ndmin可以设置初始数组的维数，
np.append(a,np.array([[0]]),axis=1)#注意append两个数组的维度要相同,axis=0:(行)只有一列，axis=1：（列）只有一行，axis数据越小越外层（越外维度）
a[x,y,z]
x为最外层
a[1,:,:]
为一个二维数组

asd1


array([40.84057632, 50.26225782, 61.49536791, 57.74773993, 42.9825765 ,
       22.21646122, 58.18248502, 40.81370729, 59.13504492, 48.14958556,
       33.88007149, 57.46449383, 67.96285364, 49.02933202, 41.51577484,
       53.50543544, 59.80578766, 35.78586873, 50.6009543 , 34.16735703,
       48.61100987, 70.85094628, 40.84723928, 46.22531357, 58.69745613,
       53.29901057, 45.65501994, 50.1971187 , 43.62586539, 51.76711581,
       61.19155643, 32.50196007, 54.92045435, 58.3697599 , 41.25055975,
       51.54941811, 64.4851078 , 64.52720904, 45.74151851, 56.90417785,
       65.61730412, 44.65459132, 37.83247632, 43.08658673, 64.5938078 ,
       62.37557309, 43.8666418 , 56.77734098, 61.95950744, 60.55615428])

In [79]:
# b=np.array([[1,2,3],[3,2,1]])
# a=np.array(np.zeros([1,2,3]),ndmin=3)
# a=np.append(a,np.array([b]),axis=0)
# a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 2., 3.],
        [3., 2., 1.]]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])