In [1]:
%matplotlib notebook

In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [22]:
n=50
A=np.zeros([n,n],dtype=np.int)

In [37]:
for i in range(50):
    for j in range(50):
        if(i!=j):
            A[i,j]=np.random.binomial(1, 0.1, 1)
A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [38]:
(A==1).sum()

247

In [41]:
np.sum(A,axis = 0)

array([ 6,  3,  8,  5,  6, 10,  2,  3,  6,  4,  5,  5,  8,  7,  8,  4,  4,
        5,  4,  8,  1,  4,  9,  4,  5,  6,  4,  4,  3,  9,  2,  3,  4,  4,
        7,  2,  6,  4,  9,  2,  3,  2,  8,  2,  4,  5,  8,  2,  5,  5])

In [45]:
A=A+A.T
for i in range(50):
    for j in range(50):
        if(A[i,j]>0):
            A[i,j]=1

In [46]:
def check_symmetric(a, tol=1e-8):
    return np.all(np.abs(a-a.T) < tol)

In [47]:
check_symmetric(A)

True

In [52]:
i=np.random.normal(50, 10,50)
i

array([55.35314105, 59.64083706, 51.57522836, 39.23464144, 38.72975973,
       49.17514869, 55.53633725, 30.60918859, 55.01093731, 40.5598242 ,
       45.78243163, 59.8801791 , 60.37531123, 40.96692991, 42.29607849,
       70.05770367, 32.22924456, 45.07944701, 32.19260777, 41.46746468,
       43.48157196, 52.48765209, 46.16024932, 52.97327589, 51.28483954,
       43.86665069, 34.64473003, 52.36189788, 49.97534491, 73.28032462,
       37.09015062, 61.97359226, 55.20674522, 50.56303352, 59.75987573,
       59.74782961, 45.43717891, 55.95487854, 59.19672809, 47.46064986,
       34.9096658 , 46.76625091, 51.58537258, 58.26115605, 55.5758369 ,
       64.5466319 , 54.44740033, 56.10893285, 51.26804134, 62.76798542])

In [53]:
import pandas as pd

In [54]:
data_A=pd.DataFrame(A)
data_i=pd.DataFrame(i)

In [55]:
data_A.to_csv("A.csv")
data_i.to_csv("i.csv")

In [57]:
np.array(data_A)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [58]:
np.sum(A,axis = 1)

array([10,  9,  9,  9, 10, 14,  5,  6, 14, 10,  8, 12, 12,  8, 13, 10,  8,
       11,  6, 13,  6, 10, 13,  8,  8, 12,  5,  8,  7, 13,  8, 10,  6,  7,
       11,  7, 10, 10, 15,  5,  4,  9, 15,  9, 12,  9, 12,  6,  8,  6])

In [59]:
def L_matrix(A):
    D=np.sum(A,axis = 1)
    for i in range(50):
        A[i,i]=-D[i]
    return -A

In [62]:
data_L=pd.DataFrame(L_matrix(A))

In [63]:
data_L.to_csv("L.csv")